### ISSUE TITLE
unpkg.com dependencies

### ISSUE THREAD

**Issue by pixeye33** [kuuji/button-card#12]
Hello,

I just set this up and noticed that it loads a few unpkg.com dependencies.

Is there a way to have all the dependencies hosted localy instead of a third party ?

Thanks !

**Comment by ohadbenita** [comment]
Would be great to have this one fixed

**Comment by kuuji** [comment]
I'm opened to suggestion in how to do this properly. I do not want to include code from third parties in my repo and what I have now is very flexible if I need to change a version. It also only downloads it only once, the next times it's cached in the browser.

What's the issue with having this remote?

**Comment by andrewjfreyer** [comment]
@kuuji Thanks again for this work - It's really quite great. The biggest issue with remote host is that certain browsers (including Safari on my end) do not cache the file. So like some users reported in the HA Forum thread, when internet goes out, the resource is unavailable and the button-card fails.

**Comment by Hypfer** [comment]
https://github.com/Hypfer/better-button-card

I've rewritten it with no external dependencies whatsoever. Have fun.

**Comment by ohadbenita** [comment]
Thanks for that ! I opened an issue in the new repo, it seems different and there seems to be some text alignment issues, I'd really appreciate if you could take a look at the screenshots I attached
