### ISSUE TITLE
FR: color_type: blank-card as label

### ISSUE THREAD

**Issue by VDRainer** [kuuji/button-card#13]
HA forum down, so posting it here.

First: GREAT WORK! I love it! :heart:

It would be nice to add a name , text and background color to the blank-card, so you can use it as label.
In the moment i use:
```
          - type: "custom:button-card"
            color_off: var(--paper-card-background-color)
            color_type: icon
            name: Esszimmer
```
as label.

Works, but is clickable and raises error in the log because there's no entity.
![auswahl_147](https://user-images.githubusercontent.com/26381449/45184471-47086000-b227-11e8-8e0e-b0dec4915f4d.png)

Just a sidenote: Why are all the characters uppercase?

**Comment by kuuji** [comment]
> It would be nice to add a name , text and background color to the blank-card, so you can use it as label.

Good suggestion. I'll look into that, or something similar for labeling.

> Just a sidenote: Why are all the characters uppercase?

That's the default for `paper-button` apparently.
You can change that easily with 

```
style:
  - text-transform: none
```
