### ISSUE TITLE
[Request] Group buttons in a card

### ISSUE THREAD

**Issue by matisaul** [kuuji/button-card#17]
Hi,
Thanks for your amazing work!

Is there any chance to group some buttons in a card, with a title? I don't know if already exist this feature or not...

Thanks in advance!

**Comment by bradyn12** [comment]
I solved this by putting the button cards in a horizontal stack card in the [Vertical-Stack-In-Card](https://github.com/custom-cards/vertical-stack-in-card) custom card. You can give a title and they'll be grouped in a card.
