### ISSUE TITLE
Card can't be used, import clause is said to be broken

### ISSUE THREAD

**Issue by ohadbenita** [kuuji/button-card#18]
This is the error I get while trying to use Button card with one of my entities :

ERROR (MainThread) [frontend.js.latest.201809160] http://x.x.x.x:8123/local/custom_ui/button-card.js?v=1:1:8 Uncaught SyntaxError: Unexpected token {

Attached is the [Chrome debugger screenshot](https://i.imgur.com/HCGMO5y.png) to emphasize

**Comment by kuuji** [comment]
@ohadbenita Can you show me your lovelace config? Especially the resources that import the card.

**Comment by ohadbenita** [comment]
Yes, my relevant lovelace config is :

  - url: /local/custom_ui/button-card.js?v=1
    type: js

`- type: "custom:button-card"
        entity: switch.livingroom_ac
        icon: mdi:home
        color: auto
        color_type: card
        default_color: rgb(255, 233, 155)
        action: more_info
        name: Home
        style:
          - font-size: 12px
          - font-weight: bold`

**Comment by ohadbenita** [comment]
You are absolutely right, thanks for this, it works now, I'll get to configuring everything using your wonderful card

Thanks a lot again and sorry...
