### ISSUE TITLE
TypeError: state is undefined

### ISSUE THREAD

**Issue by kuradi** [kuuji/button-card#19]
hassio 0.79.2
getting all the time error
`Log Details (ERROR)

Wed Oct 03 2018 22:23:58 GMT+0300 (FLE Daylight Time)

https://my.ip.address/local/button-card.js:154:26 TypeError: state is undefined`

**Comment by kuuji** [comment]
Hey @kuradi! Is that still an issue? If it is can you share more about the entity that's causing problems.
