### ISSUE TITLE
Fully Kiosk Browser fail to render button card

### ISSUE THREAD

**Issue by ohadbenita** [kuuji/button-card#26]
Hi, I've installed Fully Kiosk Browser on an Amazon Fire Tablet
I see (attached) that the button cards are rendered incorrectly, anything I should change in my setup to make it work ? 

What's needed to troubleshoot this issue ?

Thanks

**Comment by kuuji** [comment]
No he's saying it's an issue with silk / kiosk not supporting html custom elements (shadow DOM).

I would try installing chrome via an apk and see how it goes.

**Comment by ohadbenita** [comment]
I've tried with both Chrome and Silk and it's working fine, so it's
probably related to Fully Kiosk
אוהד בניטה
נייד - 0508246047

   \__/         # ##
         `(  `^=_ p _###_
          c   /  )  |   /
   _____- //^---~  _c  3
 /  ----^\ /^_\   / --,-
(   |  |  O_| \\_/  ,/
|   |  | / \|  `-- /
(((G   |-----|
      //-----\\
     //       \\
   /   |     |  ^|
   |   |     |   |
   |____|    |____|
  /______)   (_____\
