### ISSUE TITLE
Tracker.json URL in instructions wrong?

### ISSUE THREAD

**Issue by xbmcnut** [kuuji/button-card#28]
Hi there,

Your URL below is wrong so my custom updater is not seeing the new release. Don't know how to edit it or make a PR so leaving it here as an issue.

**You have:**
```
custom_updater:
  card_urls:
    - https://raw.githubusercontent.com/kuuji/button-card/0.0.2/tracker.json
```
**Shoud be?**
```
custom_updater:
  card_urls:
    - https://raw.githubusercontent.com/kuuji/button-card/master/tracker.json
```

**Comment by kuuji** [comment]
Thanks for that @xbmcnut! I fixed it on the readme and on the forum post.
