### ISSUE TITLE
overhaul of core entity-button

### ISSUE THREAD

**Issue by iantrich** [kuuji/button-card#58]
I'm fed up with entity-button, as are many others, and would like to propose moving a good chunk of your awesome work into the core entity-button. I don't think there will ever become a point where core button would be nearly as feature rich as your button-card, and hope you don't think I'm trying to run you out of business :) If anything, I'm hoping that we can make entity-button a lot better so that your custom card could actually just extended it with more awesomeness.

Any objections? I don't want to step on any toes.

I would like to do it slowly, as well, adding bits and pieces to make sure we do it smart. I, of course, would love it if you were the one to submit it to core, but know that free-time is not easily found by most devs :)

Let me know your thoughts. Thanks! 🍻

**Comment by iantrich** [comment]
@arsaboo passed along your response on the forums which makes it sound like you're okay with this. Let me know if that is not true and thanks for card.

**Comment by kuuji** [comment]
I'm ok with this @iantrich. As much as I'd like to be involved, I have a lot going on right now and don't have too much time to invest in open source.

**Comment by kuuji** [comment]
Do you have an idea of which features should be moved first? Maybe we can run a poll...

**Comment by iantrich** [comment]
I’m going to start small and just allow the hiding of name/icon and not force name to caps.

**Comment by iantrich** [comment]
And I hear on the busy part. January was crazy on my end, glad to have some free time again :)
